services:
  - type: web
    name: ground-station
    env: node
    plan: free
    buildCommand: "npm run build"
    startCommand: "npm run serve"
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: SIMULATE
        value: "false"

